<?php
$data = array(
"Quando sei in conflitto con qualcuno esiste solo un fattore che può fare la differenza tra incrinare un rapporto e distruggerlo: l'atteggiamento.","Timothy Bentley",
"I due giorni più importanti della vita sono quello in cui sei nato e quello in cui capisci perché.","Mark Twain",
"Il pessimista si lamenta al vento, l'ottimista aspetta che il vento cambi ed il realista aggiusta le vele.","Nicolas Sebastien",
"Alla domanda se io sia pessimista o ottimista, rispondo che la mia conoscenza è pessimista, ma la mia volontà e la mia speranza sono ottimiste.","Albert Schweitzer",
"Il vero ostacolo alla conoscenza non è l'ignoranza ma la presunzione di sapere.","Daniel J. Boorstin",
"Chiunque viva sinceramente e affronti senza piegarsi a dolori e delusioni è assai più degno di chi ha sempre avuto il vento favorevole, non conoscendo altro che una relativa prosperità.","Vincent Van Gogh",
"Ti accorgi di essere sereno e in pace col mondo, quando ti fermi volentieri ai semafori.","Leonardo Morini",
"Un vincitore è solo un sognatore che non si è arreso.","Nelson Mandela",
"Nei peggiori momenti ricorda: chi è capace di soffrire intensamente, è capace anche di intensa allegria.","Clarice Lispector",
"L'arte di vincere la si impara nelle sconfitte.","Simon Bolivar",
"Anche se la felicità ti dimentica un po', tu non dimenticarla mai del tutto.","Jacques Prevert",
"Quando vedi un affare di successo vuol dire che qualcuno ha preso una decisione coraggiosa.","Peter Drucker",
"La vita è come uno specchio: ti sorride se la guardi sorridendo.","Jim Morrison",
"Se vuoi vedere le valli, sali in vetta ad una montagna; se vuoi vedere la vetta di una montagna, sali su una nuvola; se invece aspiri a comprendere la nuvola, chiudi gli occhi e pensa.","Kahlil Gibran",
"Riflettere è considerevolmente laborioso, ecco perché molta gente preferisce giudicare.","José Ortega y Gasset",
"Posso insegnare come ottenere quello che si vuole dalla vita.<br />Il problema è che non riesco a trovare chi sappia dirmi cosa realmente voglia.","Mark Twain",
"La quercia è un albero possente, eppure può essere distrutta da una tempesta perché resiste agli elementi; il bambù si piega con il vento, e piegandosi sopravvive.","Bruce Lee",
"Vincere non è soltanto un verbo, è uno stato mentale.","Anonimo",
"Devi entrare in affari per te stesso: non diventerai mai ricco se lavori per altri.","J. Paul Getty",
"La solitudine è la sorte di tutti gli spiriti eminenti: talvolta essi ne sospireranno, ma la sceglieranno sempre come il male minore.","Arthur Schopenhauer",
"Il male è una scorciatoia. Il bene un percorso.","S. Tamaro",
"Vi è uno spettacolo più grandioso del mare, ed è il cielo. Vi è uno spettacolo più grandioso del cielo, ed è l'interno dell'anima.","Victor Hugo",
"Non bastano tutti i cammelli del deserto per comprarsi un amico.","(proverbio arabo)",
"La verità che ci fa liberi è quasi sempre la verità che non vorremmo udire. Perciò quando affermiamo che una cosa non è vera, molto spesso ciò significa che non ci piace.","A. de Mello",
"Il talento è come un tiratore, il quale colpisce un bersaglio che gli altri non sanno cogliere, mentre un genio è come un tiratore, il quale colpisce un bersaglio che gli altri nemmeno riescono a vedere.","Arthur Schopenhauer",
"Non andrai mai più in alto delle aspettative che hai su te stesso. Quindi aspettati sempre il meglio.","Brian Tracy",
"Tutto ciò che merita di essere fatto, merita di essere fatto bene.","Philip Dormer Chesterfield",
"Può darsi che non siate responsabili per la situazione in cui vi trovate, ma lo diventerete se non fate nulla per cambiarla.","Martin Luther King",
"Qualunque cosa vogliate fare, fatela adesso. I domani sono contati.","Michael Landon",
"Vivere è la cosa più rara al mondo. La maggior parte della gente esiste, e nulla più.","Oscar Wilde",
"La libertà esiste se esistono uomini liberi, muore se gli uomini hanno l'animo di servi.","Luigi Einaudi",
"Nessun vento è favorevole per chi non sa dove andare, ma per noi che sappiamo, anche la brezza sarà preziosa.","R.M. Rilke",
"Le persone diventano veramente eccezionali quando cominciano a pensare di poter fare le cose. Credere in se stessi è il primo segreto del successo.","Norman Vincent Peale",
"Ciò che logora le nostre anime nel modo più rapido e peggiore possibile è perdonare senza dimenticare.","Arthur Schnitzler",
"La felicità non è nient'altro che il piacere diviso con un altro.","J. Dolent",
"Non abbassare mai i tuoi standard per compiacere gli altri.","Vincent Lombardi",
"Ognuno di noi ha un paio di ali ma solo chi sogna impara a volare.","Jim Morrison",
"Noi pretendiamo che la vita debba avere un senso: ma la vita ha precisamente il senso che noi stessi siamo disposti ad attribuirle.","Hermann Hesse",
"Se non si rischiasse mai nella vita, Michelangelo avrebbe dipinto il pavimento della cappella Sistina.","Neil Simon",
"Il falso amico è come l'ombra che ci segue finché dura.","Carlo Dossi",
"Non importa quanto profondo e con quanta foga scaverai il pozzo: se non troverai l'acqua morirai di sete.","(proverbio cinese)",
"La parola giusta può essere efficace, ma nessuna parola è tanto efficace quanto un silenzio al momento giusto.","Mark Twain",
"Più mi esercito, più divento fortunato.","Gary Player",
"Artista è soltanto chi sa fare della soluzione un enigma.","Karl Kraus",
"Non si ricordano i giorni, si ricordano gli attimi.","Cesare Pavese",
"Chi parla a lungo da solo in presenza di altri senza adulare gli ascoltatori, si rende antipatico.","Johann Wolfgang von Goethe",
"Io sono solo un piccolo uomo che fa piccole cose, ma è dalle piccole cose che nascono quelle grandi.","Michele Tommasini",
"Soltanto un uomo che sa cosa vuol dire essere sconfitti può raggiungere il fondo della sua anima ed uscirne con un oncia extra di energia necessaria a vincere quando il combattimento è pari.","Muhammad Alì",
"La vita non è come dovrebbe essere. È quella che è. È il modo in cui l'affronti che fa la differenza.","Virginia Satir",
"Non devi rinnegare il passato, per ricostruire il tuo futuro.","dal film ''Furia eslosiva''",
"Alla base di ogni fortuna c'è la fede di un uomo che ha creduto in sé stesso, che ha creduto in un'idea, in un sogno, per quanto folle potesse sembrare agli altri.","Mark Fisher",
"Senza un temporale di tanto in tanto, come faremmo ad apprezzare i giorni di sole?","Kevin Alan Milne",
"Il pensiero è sempre un grano di sabbia nell'ingranaggio del potere.","Bruno Arpaia",
"Il successo è poter coricarsi ogni sera con l'anima in pace.","Paulo Coelho",
"Si hanno a disposizione dieci minuti per mettere in atto un'idea prima che questa ritorni nel mondo dei sogni.","Richard Buckminster Fuller",
"Sognate e la realtà supererà i vostri sogni.","Josemaria Escriva",
"Chiunque conservi la capacità di cogliere la bellezza non sarà mai vecchio.","Kafka Franz",
"Qualunque cosa, piccola o grande che sia, diventa un'avventura se viene condivisa con la persona giusta.","Kathleen Norris",
"Avrai dei momenti difficili, ma ti faranno apprezzare le cose belle alle quali non prestavi attenzione.","Will Hunting - Genio ribelle",
"Ci sono pericoli in ogni cosa che si fa, ma ci sono pericoli ancora più grandi nel non fare nulla.","Shirley Williams",
"Il perfetto uomo di mondo sarebbe colui che non fosse mai né dubbioso né precipitoso nel prendere le sue decisioni.","Arthur Schopenhauer",
"Sono più quelli che muoiono nella fuga che non quelli che muoiono combattendo.","Selma Legerlof",
"Non è vero che abbiamo poco tempo: la verità è che ne perdiamo molto","Seneca",
"Non è la libertà che manca, mancano gli uomini liberi.","Leo Longanesi",
"La motivazione vincerà sempre sul talento.","Norman R. Augustine",
"Ciò che non abbiamo osato, abbiamo certamente perduto.","Oscar Wilde",
"Afferra il presente e affidati al domani il meno possibile.","Orazio",
"L'uomo destinato alla gloria non teme la povertà, anzi la miseria, perché sa che nella miseria il suo ingegno diventerà genio.","Carlo Dossi",
"Il vero atto della scoperta non consiste nel trovare nuovi territori, ma nel vedere con occhi nuovi.","Marcel Proust",
"Perdi i tuoi soldi e hai perso solo i tuoi soldi, ma perdi tempo e hai perso una parte della tua vita.","Michael Leboeuf",
"Nessuno può mostrare troppo a lungo una faccia a se stesso e un'altra alla gente senza finire col non sapere quale sia quella vera.","Nathaniel Hawthorne",
"È proprio quando credete di sapere qualcosa che dovete guardarla da un'altra prospettiva.","dal film ''L'attimo fuggente''",
"Se dovessi darti un consiglio, ti direi: non lasciarti intimidire dalle opinioni altrui. Poiché solo la mediocrità cerca conferme, affronta i rischi e fa' quello che desideri.","Paulo Coelho",
"Prima di intraprendere qualcosa rifletti attentamente e dopo aver riflettuto agisci subito.","Sallustio",
"Sorridetevi l'un l'altro, sorridete a vostra moglie, sorridete a vostro marito, sorridete ai figli, sorridetevi l'un l'altro, non importa chi sia, e questo vi aiuterà a crescere con più amore l'uno per l'altro.","Madre Teresa di Calcutta",
"Soltanto l'ardente pazienza porterà al raggiungimento di una splendida felicità.","Pablo Neruda",
"O cavalchi la vita o essa cavalca te. Il tuo atteggiamento mentale determina chi è il cavaliere e chi il cavallo.","Napoleon Hill",
"Non c'è notte così lunga da impedire al giorno di risorgere.","Lorenzo Tramaglino",
"Non cercare di diventare un uomo di successo, ma piuttosto un uomo di valore.","Albert Einstein",
"Non cercate la colpa, cercate la soluzione.","Henry Ford",
"La vita è troppo breve per prendersela per uno stupido errore.","Andy Warrol",
"Fede è fare il primo scalino anche quando non vedi l'intera scala.","Martin Luther King",
"Non crediate che colui che tenta di confortarvi, viva senza fatica in mezzo alle parole semplici e calme, che qualche volta vi fanno bene. La sua vita reca molta fatica e tristezza e resta lontana dietro a loro. Ma fosse altrimenti, egli non avrebbe potuto trovare quelle parole.","R.M. Rilke",
"Quando un bambino capisce che gli adulti sono imperfetti, diventa adolescente. Quando li perdona, diventa adulto. Quando perdona se stesso, diventa saggio.","Alden Nowlan",
"L'aquila non può levarsi a volo dal piano terra, bisogna che saltelli faticosamente su una roccia o su un tronco d'albero: ma da lì si lancia alle stelle.","Hugo von Hofmannsthal",
"Essere se stessi è una virtù esclusiva dei bambini, dei matti e dei solitari.","Fabrizio De André",
"I dolori, le delusioni e la malinconia non sono fatti per renderci scontenti e toglierci valore e dignità, ma per maturarci.","Hermann Hesse",
"Sono una parte di tutto ciò che ho trovato sulla mia strada.","Alfred Tennyson",
"Dobbiamo abituarci all'idea che ai più importanti bivi della nostra vita non c'è segnaletica.","Ernest Hemingway",
"La vita non deve essere un romanzo impostaci, bensì un romanzo fatto da noi.","Novalis",
"Solo il dolore fa crescere, ma il dolore va preso di petto, chi svincola o si compiange è destinato a perdere.","Susanna Tamaro",
"Nessuno ha amore più grande di colui che sa rispettare la libertà dell'altro.","Simone Weil",
"Un giorno senza risata è un giorno sprecato!","Charles Spencer Chaplin",
"Comincia fin da ora ad essere quello che sarai in futuro.","S. Gerolamo",
"La differenza tra una persona di successo e gli altri non sta nella mancanza di forza o nella mancanza di conoscenza ma piuttosto nella mancanza di volontà.","Vincent Lombardi",
"Le cose che contano di più non devono essere mai alla mercé di cose che contano meno.","Johann Wolfgang von Goethe",
"Colui che governa gli altri dovrebbe per prima cosa essere il padrone di se stesso.","Philip Massinger",
"La grandezza non consiste nell'essere questo o quello, ma nell'essere se stesso, e questo ciascuno lo può se lo vuole.","S. Kierkegaard",
"Smettila di pensare a cosa potrebbe andare male e inizia a pensare a cosa potrebbe andare bene.","Roberto Benigni",
"Il vero orrore è quello di un mondo in cui è proibito leggere, dunque è proibito conoscere, amare, ricordare.","François Truffaut",
"Se un uomo non ha scoperto qualcosa per cui è disposto a morire, non è degno di vivere.","Martin Luther King",
"Quando in un'azienda una persona è indispensabile, vuol dire che l'azienda è organizzata male.","Roberto Niederer",
"Secondo alcuni autorevoli testi di tecnica di aeronautica, il calabrone non può volare, a causa della forma e del peso del proprio corpo in rapporto alla superficie alare. Ma il calabrone non lo sa e perciò continua a volare.","Igor Sikorsky",
"L'amore piace più del matrimonio, per la stessa ragione che i romanzi piacciono più dei libri di storia.","Nicolas de Chamfort",
"Un ramo di follia abbellisce l'albero della saggezza.","(proverbio uzbeco)",
"Impara le regole come un professionista, affinché tu possa infrangerle come un artista.","Pablo Picasso",
"Per apparire onesti bisogna esserlo.","Jean de la Bruyere",
"Se pensi che l'educazione sia costosa, aspetta e vedrai quanto ti costerà la tua ignoranza.","John M. Capozzi",
"La cosa seccante di questo mondo è che gli imbecilli sono sicuri di sé, mentre le persone intelligenti sono piene di dubbi.","Bertrand Russel",
"Colui che non sbaglia mai perde un sacco di buone occasioni per imparare qualcosa.","Thomas Alva Edison",
"C'è un solo tipo di successo: quello di fare della propria vita ciò che si desidera.","Henry David Thoreau",
"Tutti i nostri sogni possono diventare realtà, se abbiamo il coraggio di inseguirli.","Walt Disney",
"Se la povertà è la madre dei delitti, lo scarso impegno ne è il padre.","Jean de la Bruyere",
"Un uomo senza una meta è come una nave senza timone.","Shiller",
"Amate chi siete e quello che siete, amate quello che fate. Ridete di voi stessi e della vita, e nulla potrà mai toccarvi.","Louise Hay",
"L'amore è un frutto che matura in ogni stagione ed è sempre alla portata di ogni mano.","Madre Teresa di Calcutta",
"Se impari da ogni sconfitta, non avrai mai realmente perso.","Zig Ziglar",
"Compiangere se stessi e la situazione in cui ci si trova non è solo uno spreco di energie ma anche l'abitudine peggiore che si possa avere.","Dale Carnegie",
"Gli sbagli sono un fatto della vita. È la risposta allo sbaglio quella che conta.","Nikki Giovanni",
"Arricchiamoci delle nostre reciproche differenze.","Paul Valéry",
"Il successo è un viaggio, non una destinazione.","Dale Carnegie",
"La natura ha dato all'uomo due estremità: una su cui sedere e una con cui pensare. Fin da allora il successo o il fallimento dell'uomo sono dipesi da quella che ha usato di più.","Kirkpatrik",
"Volevo ricordarti che l'amore è rimanere e non sparire per vedere se uno poi ci tiene.","Charles Bukowski",
"L'importanza del viaggio non sta tanto nel sapere dove siamo, ma verso quale direzione stiamo andando, senza perdere nulla di ciò che troviamo durante il percorso.","Romano Battaglia",
"Quando una porta si chiude, altre si aprono, ma spesso passiamo troppo tempo ad osservare la porta chiusa tanto da non vedere quelle che si stanno aprendo per noi.","Alexander Bell",
"Il futuro si costruisce un giorno per volta.","Dean Acheson",
"Non è la vittoria che conta, bensì la tenacia e il coraggio coi quali abbiamo lottato.","S. Teresa",
"Prima di giudicare la mia vita o il mio carattere, mettiti le mie scarpe e percorri il cammino che ho percorso io. Vivi il mio dolore, i miei dubbi e le mie risate. Vivi gli anni che ho vissuto io e cadi là dove sono caduto io e rialzati come ho fatto io.","Luigi Pirandello",
"Ogni volta che capite che state dalla parte della maggioranza, vi conviene fermarvi e riflettere.","Mark Twain",
"Devi dedicare del tempo al tuo prossimo: anche se e' una cosetta da niente, fa qualcosa per gli altri; qualcosa per cui non ricavi alcun compenso se non il privilegio di farlo.","Albert Schweitzer",
"Quello che parla impulsivamente assomigliasi al cacciatore che spara senza puntare.","Montesquieu",
"Dire la verità in malafede dovrebbe essere considerato disonesto.","Karl Kraus",
"L'esperto è una persona che ha fatto in un campo molto ristretto tutti i possibili errori.","Niels Bohr",
"Siamo al mondo per essere veri, non perfetti.","Erich Linder",
"Non importa quanto sia freddo l'inverno, dopo c'è sempre la primavera.","Eddie Vedder",
"Ritieniti soddisfatto dell'agire bene, e lascia che gli altri parlino di te come fa loro piacere.","Pitagora",
"Tutte le risposte sono a nostra disposizione, basta solo scegliere le domande giuste per vincere.","Anthony Robbins",
"Un leader aspira ad essere un esempio più che un eroe.","Anonimo",
"Tante persone pensano a come cambiare l'umanità, pochi pensano a come cambiare se stessi.","Lev N. Tolstoj",
"Se puoi sognarlo, puoi farlo.","Walt Disney",
"Non mi scoraggio perché ogni tentativo sbagliato scartato è un altro passo avanti.","Thomas Alva Edison",
"Sii ciò che sei e di' ciò che senti, perché quelli a cui importa non contano e a quelli che contano non importa.","Bernard Baruch",
"La misura dell'intelligenza è data dalla capacità di cambiare quando è necessario.","Albert Einstein",
"Libertà significa accettare una serie di grandi responsabilità.","Sheldan Nidle",
"Ciò che conta non è quanti anni ci sono nella tua vita, ma quanta vita nei tuoi anni.","Abramo Lincoln",
"Chi ama e chiede contraccambio è un ricco che mendica da un povero.","Camillo Sbarbaro",
"Se un uomo parte con delle certezze, finirà con dei dubbi; ma se si accontenta di iniziare con qualche dubbio, arriverà alla fine con delle certezze.","Francis Bacon",
"Noi invidiamo la felicità degli altri, senza sapere che gli altri invidiano la nostra.","P. Siro",
"Stai attento a quello che cerchi, potresti trovarlo.","Oscar Wilde",
"Ti amo non solo per quello che tu sei, ma per quello che io sono quando sono con te.","Elizabeth Barrett Browning",
"La cosa migliore che puoi fare per le persone a cui vuoi bene è diventare una persona felice e gioiosa.","Brian Tracy",
"Lo straordinario risiede nel cammino delle persone comuni.","Paulo Coelho",
"Il difficile non è essere intelligenti, ma sembrarlo.","Luc de Clapiers de Vauvenargues",
"Al mattino, non appena ti svegli, soffermati a pensare ai privilegi di cui godi: essero vivo, poter pensare, godere delle cose, amare.","Marco Aurelio",
"Nella vita nulla è costante se non il Cambiamento.","Buddha",
"Impara dagli errori degli altri: non puoi vivere cosi' a lungo da farli tutti da te.","Eleanor Roosvelt",
"Solo chi detiene fortemente il timone della propria esistenza può navigare nei mari più agitati senza subire danni.","I ching",
"Sembra che tutti abbiano l'idea esatta di come dobbiamo vivere la nostra vita. E non sanno mai come devono vivere la loro.","Paulo Coelho",
"L'eleganza non è farsi notare, ma farsi ricordare.","Giorgio Armani",
"Nessuno può approdare a niente nella vita senza che qualcun altro creda in lui.","Paul Auster",
"Amare significa comunicare con l'altro e scoprire in lui una parte di noi e una particella di Dio.","Paulo Coelho",
"Il genio è un uno per cento di ispirazione e il novantanove per cento di sudore.","Thomas Alva Edison",
"Nel potere di cambiare te stesso, risiede il potere di cambiare il mondo che ti circonda.","Anwar Sadat",
"Avrei potuto accontentarmi, ma è così che si diventa infelici.","Charles Bukowski",
"Chiudi alcune porte. Non per orgoglio, ma perché non sono più adatte alla tua vita.","Paulo Coelho",
"Gli ostacoli sono fatti per essere superati.","J. Willard Marriot",
"Nessuno invoca la libertà di stampa, se non colui che vuole abusarne.","Johann Wolfgang von Goethe",
"Dio giudica l'albero dai frutti, non dalle radici.","Paulo Coelho",
"Si comincia col disimparare ad amare gli altri e si finisce con non trovare più niente in noi stessi degno di essere amato.","Friedrich Nietzsche",
"Di sera i pulcini e le galline tornano al pollaio; lo stesso fanno i pensieri dell'uomo, quindi fate attenzione ai pensieri che fate circolare di giorno.","Napoleon Hill",
"I libri e la mente funzionano solo se sono aperti.","James Deward",
"La magia è credere in sè stessi: se riusciamo a farlo, allora possiamo far accadere qualsiasi cosa.","Johann Wolfgang von Goethe",
"Ci si mette un sacco di tempo a diventare giovani.","Pablo Picasso",
"L'inizio è la parte più importante del lavoro.","Platone",
"L'uomo che non è contento di poco, non è contento di nulla.","Epicuro",
"Qualunque cosa tu possa fare, o sognare di fare, incominciala. L'audacia ha in sé genio, potere e magia. Incominciala adesso.","Johann Wolfgang von Goethe",
"La forza si schiera dalla parte di coloro che credono nel giusto.","Napoleon Hill",
"È lontano solo ciò che non ci interessa veramente raggiungere.","Paul Mehis",
"Se desiderate tanto felicità e serenità non capite che non sono in nessun altro luogo al di fuori di voi stessi?","Richard Bach",
"L'amore che non si rinnova ogni giorno diviene abitudine e poi schiavitù.","Kahlil Gibran",
"Quando le persone vi dicono chi sono, credeteci. Ma è altrettanto importante che non gli crediate quando cercano di dirvi chi siete voi.","Maria Popova",
"Una famiglia unita è sempre più numerosa di una famiglia divisa.","(proverbio cinese)",
"Da' alle persone più di quello che si aspettano e fallo con gusto.","Anonimo",
"Ogni grande e rilevante momento nella storia del mondo è il trionfo di qualche entusiasmo.","Ralph Waldo Emerson",
"La felicità nasce dall'altruismo e l'infelicità dall'egoismo.","C. Mouni",
"Il vero modo per farsi ingannare è di credersi piu' furbi degli altri.","Francois de La Rochefoucald",
"Non è quanto si possiede, ma quanto si assapora a fare la felicità.","Charles Spurgeon",
"Se tu desideri sempre quello che non hai, e disprezzi quello che hai, la tua vita trascorre senza pienezza e senza gioia; e poi, d'improvviso, la morte viene al tuo capezzale prima che tu possa sentirti pronto ad andartene contento ed appagato.","Lucrezio",
"Un sogno che si sogna da solo è solamente un sogno, però un sogno che si sogna insieme è realtà che comincia.","Raul Seixas",
"Chi sa ascoltare non soltanto è simpatico a tutti, ma dopo un po' finisce con l'imparare qualcosa.","Wilson Mizner",
"La vera sincerità, quando occorre, va difesa con piccole bugie.","Giacomo De Benedetti",
"Insistere è testardaggine. Perseverare è determinazione.","Jacinto Benavente",
"Un marinaio non prega per il vento buono. Impara a navigare.","Gustav Lindborg",
"L'azione è la chiave fondamentale di ogni successo.","Anthony Robbins",
"Divertiti nel percorso, divertiti ogni momento e smettila di preoccuparti di vincere o perdere.","Matt Biondi",
"La qualità della vita di un uomo è in diretta proporzione al suo impegno ad eccellere, indipendentemente dall'attività da lui scelta.","Vincent Lombardi",
"La nuvola nasconde le stelle e canta vittoria ma poi svanisce: le stelle durano.","Rabindranath Tagore",
"Non potrete mai perdere due delle risorse più importanti che avete: la forza della vostra mente e la libertà di utilizzarla.","Napoleon Hill",
"L'esser contenti è una ricchezza naturale, il lusso è una povertà artificiale.","Socrate",
"Le persone di successo hanno l'abitudine di fare le cose che i falliti non amano fare.","Stephen Covey",
"La disperazione più grave che possa impadronirsi di una società è il dubbio che vivere onestamente sia inutile.","Corrado Alvaro",
"Una cosa buona non ci piace quando non ne siamo all'altezza.","Friedrich Nietzsche",
"Non è quello che ti succede che determina il tuo futuro, ciò che conta è cosa ne fai.","Jim Rohn",
"Le battaglie della vita non vanno sempre al più forte o al più veloce. Ma presto o tardi l'uomo che vince è quello che ha pensato di poter vincere.","Vincent Lombardi",
"Il vero segreto del successo è avere entusiasmo e passione.","Walter Chrysler",
"Vivere rimane un'arte che ognuno deve imparare, e che nessuno può insegnare.","Havelock Ellis",
"Bisogna trovare il proprio sogno perché la strada diventi facile. Ma non esiste un sogno perfetto. Ogni sogno cede il posto a un sogno nuovo, e non bisogna volerne trattenere alcuno.","Hermann Hesse",
"A volte basta la parola di qualcuno che creda in te per rimetterti al mondo.","Alessandro D'Avenia",
"La libertà è come il mare; non può essere rinchiusa. E come il mare, un uomo libero lo è per sempre.","Humbert du Charbon",
"Se si vuole riuscire in questo mondo non bisogna essere molto più intelligenti degli altri, bisogna solo essere in anticipo di un giorno.","Leo Szilard",
"La mente che funziona meglio è quella che viene utilizzata di più.","Napoleon Hill",
"Nella vita è estremamente stimolante far quello che la gente dice che non puoi fare.","Romano Battaglia",
"Le persone oneste e intelligenti difficilmente fanno una rivoluzione, perché sono in minoranza.","Aristotele",
"C'è vero progresso solo quando i vantaggi di una nuova tecnologia diventano per tutti.","Henry Ford",
"Più tardi sarà troppo tardi. La nostra vita è ora.","Jacques Prevert",
"L'esperienza è il tipo di insegnante più difficile. Prima ti fa l'esame, e poi ti spiega la lezione.","Oscar Wilde",
"Se non sai dove stai andando, come puoi arrivarci?","Basil S. Walsh",
"L'aquila vola solitaria, la pecora cammina in gregge.","Anonimo",
"Se cerchi sempre di essere normale, non saprai mai quanto puoi essere straordinario.","Maya Angelou",
"Non giudico le persone dai loro errori ma dalla loro voglia di rimediare.","Bob Marley",
"Ricorda che non ottenere quel che si vuole può essere talvolta un meraviglioso colpo di fortuna.","Dalai Lama",
"Felici e forti quelli che accettano con animo uguale la sconfitta e la vittoria.","Jorge Luis Borges",
"Quello che il bruco chiama fine del mondo, il resto del mondo chiama farfalla.","Lao-Tse",
"Non fare l'errore di considerare ogni giorno uguale all'altro. Ogni giorno porta con sé un miracolo nascosto.","Og Mandino",
"Solo chi non osa non sbaglia.","Henry Ford",
"Vai con fiducia nella direzione dei tuoi sogni! Vivi la vita che hai immaginato.","Henry David Thoreau",
"La ricchezza assomiglia all'acqua di mare: quanto più se ne beve, tanto più si ha sete.","Arthur Schopenhauer",
"Su ciò di cui non si può parlare è bene tacere.","Ludwig Wittgenstein",
"La vera felicità è godersi il presente, senza dipendere ansiosamente dal passato.","Seneca",
"Continua a piantare i tuoi semi, perché non saprai mai quali cresceranno.","Albert Einstein",
"L'audacia è la capacità di agire nel modo migliore anche quando le paure ci bloccano.","Omar Bradley",
"Tre sono i mezzi per comunicare l'amore: parola, vista e tatto. Il più importante è la parola. Non saprai mai infatti quanto una persona ti ama se non te lo dice.","Fulton Sheen",
"Se siete tanto fortunati da trovare il tipo di vita che vi piace, dovreste anche trovare il coraggio di viverla.","John Irving",
"Ciò che differenzia i vincenti dai perdenti è l'intraprendenza.","Anthony Robbins",
"Getta un seme e la terra ti porgerà un fiore. Sogna il tuo sogno rivolto verso il cielo, ed esso recherà a te la tua amata.","Kahlil Gibran",
"Ognuno vale tanto quanto le cose cui da importanza.","Marco Aurelio",
"Agisci in modo che ogni tuo atto sia degno di diventare un ricordo.","Immanuel Kant",
"I tuoi unici limiti sono quelli che crei nella mente o che ti lasci imporre dagli altri!","Og Mandino",
"Sarebbe bello parlare con i bambini che eravamo e chiedere loro che cosa ne pensano degli adulti che siamo diventati.","Juan Felipe Gabanhia",
"Non c'è nulla di nobile nell'essere superiore a un altro uomo. La vera nobiltà sta nell'essere superiore alla persona che eravamo fino a ieri.","Samuel Johnson",
"Accettate le sfide se volete provare l'eccitazione e il gusto della vittoria.","George S. Patton",
"Niente può aggiungere maggior potere alla tua vita come concentrare tutte le tue energie su di un preciso gruppo di obiettivi.","Nido Qbein",
"Pensare è il lavoro più arduo che ci sia, ed è probabilmente questo il motivo per cui così pochi ci si dedicano.","Henry Ford",
"Non è perché le cose sono difficili che non osiamo. È perché non osiamo che ci sembrano difficili.","Seneca",
"Non ho paura della cattiveria dei malvagi ma del silenzio degli onesti.","Martin Luther King",
"Le cicatrici che ti procuri esercitando il tuo coraggio non ti faranno mai sentire inferiore.","D.A. Battista",
"Niente imprime una cosa così intensamente nella memoria quanto il desiderio di dimenticarla.","Michel de Montaigne",
"Quando ogni risorsa fisica e mentale è ben focalizzata, il potere di risolvere i problemi si moltiplica tremendamente.","Norman Vincent Peale",
"We can be heroes, just for one day.<br />(Possiamo essere eroi, solo per un giorno).","Heroes - David Bowie ",
"Un uomo che non legge buoni libri non ha alcun vantaggio rispetto all'uomo che non sa leggere.","Mark Twain",
"Porsi un obiettivo è la più forte forza umana di auto motivazione.","Paul J. Meyer",
"Non è necessario avere una religione per avere una morale. Perché se non si riesce a distinguere il bene dal male, quella che manca è la sensibilità, non la religione.","Margherita Hack",
"Ogni lettore, quando legge, legge se stesso. L'opera dello scrittore è soltanto una specie di strumento ottico che è offerto al lettore per permettergli di discernere quello che, senza libro, non avrebbe forse visto in se stesso.","Marcel Proust",
"Ci si innamora non incontrando la persona perfetta, ma vedendo la perfezione in una persona imperfetta.","Sam Keen",
"Un problema è una possibilità che ti viene offerta per fare meglio.","Duke Ellington",
"Di regola, le avversità rivelano il genio e la prosperità lo cela.","Orazio",
"Per ogni minuto che passiamo in preda alla rabbia, perdiamo sessanta secondi felici.","William Somerset Maugham",
"Forse Dio vuole che tu conosca molte persone sbagliate prima di conoscere la persona giusta in modo che, quando finalmente la conoscerai, tu sappia esserne grato.","G. Marquez",
"Ogni uomo dovrebbe essere compiaciuto di sé stesso e felice di esserlo: essere consapevoli della propria grazia rende luminosi.","Johann Wolfgang von Goethe",
"Solo la strada del servizio agli altri porta al paese della felicità.","Napoleon Hill",
"Lo sforzo ripaga pienamente soltanto quando qualcuno rifiuta di mollare.","Napoleon Hill",
"Il dolore di chi ha offeso offre scarso sollievo a chi della dura offesa porta la croce.","William Shakespeare",
"Essere onesto può non farti avere molti amici, ma ti farà avere quelli giusti.","John Lennon",
"Ho imparato a rispettare le idee altrui, ad arrestarmi davanti al segreto di ogni coscienza, a capire prima di discutere, a discutere prima di condannare.","Norberto Bobbio",
"Per conoscere tutto di se stessi bisogna sapere tutto degli altri.","Oscar Wilde",
"Avere successo può voler dire uscire dalle fila e marciare al suono del proprio tamburino personale.","Keith DeGreen",
"Quello che facciamo in vita riecheggia nell'eternità.","dal film ''Il gladiatore''",
"Vedi, a me non interessa sentirmi intelligente ascoltando dei cretini che parlano. Preferisco sentirmi cretino ascoltando una persona eccelsa che parla.","Franco Battiato",
"Sei sempre libero di scegliere cosa fare della tua vita. Per cambiare il tuo futuro fai una scelta oggi.","Brian Tracy",
"Quando l'immagine che hai di te stesso migliora, anche i risultati che otterrai miglioreranno.","Zig Ziglar",
"Il duro lavoro è il prezzo da pagare per il successo. Penso che tu possa portare a termine ogni impresa se sei disposto a pagarne il prezzo.","Vincent Lombardi",
"Le esperienze che contano sono spesso quelle che non avremmo mai voluto fare, non quelle che decidiamo noi di fare.","Alberto Moravia",
"I bambini sono impegnati col gioco, i giovani col sesso, gli adulti con le preoccupazioni, gli anziani con la provvidenza: mai nessuno che trovi un po' di tempo per Dio.","Paramansa Yogananda",
"Nessuno ci fa del male. Siamo noi che ci facciamo del male perché facciamo cattivo uso del grande potere che abbiamo, il potere di scegliere.","J. Martin Kole",
"Genio è colui che sa far diventare semplice ciò che è complicato.","C.W. Ceran",
"Mantenere la stima di sé è il modo migliore per stare bene con se stessi.","Dacia Maraini",
"Cambiate età ogni giorno. Siate nonne a quindici anni e fidanzate a ottanta. Ma non siate mai quello che vogliono gli altri.","Barbara Alberti",
"Non ci è permesso scegliere la cornice del nostro destino. Ma ciò che vi mettiamo dentro è nostro.","Dag Hammarskjöld",
"È meglio aver amato e perduto che non aver mai amato.","S. Butler",
"La vera comunicazione ha luogo soltanto fra persone di uguali sentimenti, di ugual pensiero.","Novalis",
"La cosa più preziosa che puoi fare è un errore: non imparerai nulla dall'essere perfetto.","Adam Osborne",
"L'errore è una pianta tenace: fiorisce in ogni suolo.","M. Tupper",
"Ascolta sempre gli esperti. Loro ti diranno che cosa non si può fare, e perché. Poi fallo pure.","Robert A. Heinlein",
"Vi mostrerò un filtro d'amore senza veleni o filtri magici. Eccolo: se volete essere amati, amate.","Seneca",
"L'umiltà è la virtù più difficile da conquistare, infatti niente è più duro a morire del desiderio di pensar bene di se stessi.","Thomas Eliot",
"Potete giudicare quanto intelligente è un uomo dalle sue risposte. Potete giudicare quanto è saggio dalle sue domande.","Naguib Mahfuz",
"I falliti si dividono in due categorie: coloro che hanno agito senza pensare e coloro che hanno pensato senza agire.","John Charles Salak",
"Nulla contribuisce a tranquillizzare la mente quanto uno scopo preciso, un punto sul quale l'anima possa fissare il suo occhio.","Mary Wollstonecraft Shelley",
"Non esiste notte o problema capace di sconfiggere l'alba o la speranza.","Bern Williams",
"Scritta in cinese la parola 'crisi' è composta di due caratteri. Uno rappresenta il pericolo e l'altro rappresenta l'opportunità.","John Fitzgerald Kennedy",
"Al giorno d'oggi la gente sa il prezzo di tutto e non conosce il valore di niente.","Oscar Wilde",
"Mai ti è dato un desiderio senza che ti sia dato anche il potere di realizzarlo.","Richard Bach",
"È facile scrivere i propri ricordi, quando si ha una cattiva memoria.","Arthur Schnitzler",
"I tre grandi elementi essenziali alla felicità in questa vita sono qualcosa da fare, qualcosa da amare, e qualcosa da sperare.","Joseph Addison",
"Il segreto del canto risiede tra la vibrazione della voce di chi canta e il battito del cuore di chi ascolta.","Kahlil Gibran",
"Se vien meno nei giorni dell'avversità, la tua forza è veramente poca.","Salomone",
"Il vero amore consiste nel volere che la persona amata sia com'è e non come ci farebbe comodo che fosse.","Alberto Moravia",
"I pensieri che scegliamo sono gli strumenti che usiamo per dipingere la tela della nostra vita.","Louise Hay",
"Le idee ispirate dal coraggio sono come le pedine negli scacchi, possono essere mangiate ma anche dare avvio ad un gioco vincente.","Johann Wolfgang von Goethe",
"È ricercando l'impossibile che l'uomo ha sempre realizzato il possibile. Coloro che si sono saggiamente limitati a ciò che appariva loro come possibile, non sono mai avanzati di un solo passo.","Michail Bakunin",
"L'Entusiasmo è come la benzina. Se lo usate nel modo giusto, può fare delle cose magnifiche, ma se lo spargete in modo sconsiderato, correte il rischio di fare dei disastri.","Napoleon Hill",
"Una scelta conduce ad una nuova serie di circostanze possibili. Con mente lucida, puoi fare qualsiasi cosa.","Dalai Lama",
"La coscienza non ti trattiene dal compiere un peccato, però ti impedisce di godertelo.","Salvador de Madariaga",
"Le avversità possono essere delle formidabili occasioni.","Thomas Mann",
"I fanciulli trovano il tutto anche nel niente, gli uomini il niente nel tutto.","Giacomo Leopardi",
"Il cervello è un organo meraviglioso: nella maggior parte della gente comincia a funzionare appena si sveglia e si ferma solo quando arriva in ufficio.","Robert Frost",
"Tutti gli uomini commettono degli errori, solo i più intelligenti imparano da essi.","Winston Churcill",
"Un sorriso costa meno dell'elettricità e dà più luce.","(proverbio scozzese)",
"La suprema felicità della vita è il sapere di essere amati per quello che si è, o meglio, di essere amati a dispetto di quello che si è.","Victor Hugo",
"Le persone raramente raggiungono il successo a meno che non si divertano nel fare ciò che stanno facendo.","Dale Carnegie",
"Lo sai chi potrà salvare il mondo? L'uomo che coltiva il suo campo di grano, chi è contento di ciò che possiede, il vecchio che legge una poesia, chi accarezza un animale, chi sa perdonare, chi rende felici gli altri.","Romano Battaglia",
"La felicità non dipende da quello che ci manca, ma dal buon uso che facciamo di quello che abbiamo.","Arnaud Desjardins",
"Non diventare vittima di te stesso, non pensare al ladro che potresti incontrare per strada.","Jim Rohn",
"I sensi non ingannano, inganna il giudizio.","Johann Wolfgang von Goethe",
"Se vuoi essere amato, ama!","Seneca",
"Il parsimonioso è il più ricco degli uomini, l'avaro il più povero.","Nicolas de Chamfort",
"L'importante non è avere tante idee, ma di viverne una.","Ugo Bernasconi",
"Ogni problema contiene in sé il seme della sua soluzione.","Brian Tracy",
"Dimentica le sconfitte di ieri, ignora i problemi di domani. Vivi oggi, facendo di questo giorno il migliore dell'anno.","Og Mandino",
"La responsabilità della tua vita e di ciò che ottieni si trova in una sola persona: te stesso.","Chris Widener",
"Non si può descrivere la passione, la si può solo vivere.","Enzo Ferrari",
"'Meglio' è peggiore di 'Buono'.","Anonimo",
"L'unico vantaggio di invecchiare è che si impara a distinguere quello che conta da quello che non conta.","Edith Wharton",
"Il procrastinare è una delle malattie più comuni e più mortali e il suo effetto nefasto sul successo e sulla felicità è molto grande.","Wayne W.Dyer",
"Il miglior amico è colui che tira fuori il meglio di me.","Henry Ford",
"Quando con certe persone si è fatto il possibile per conquistarle, se la cosa non riesce c'è ancora una risorsa: non far più nulla.","Jean de la Bruyere",
"Dove regna l'amore si può raggiungere anche l'impossibile.","(proverbio Indiano)",
"Dimmi e dimenticherò. Insegnami e forse ricorderò. Coinvolgimi e imparerò.","Benjamin Franklin",
"Vivere strategicamente non è opportunismo e non significa mentire, ma è un atto del guerriero che prende le sembianze e compie gli atti che la situazione richiede. Solo chi vive strategicamente può sopravvivere.","Silvio Berlusconi",
"Le menti mediocri condannano abitualmente tutto ciò che oltrepassa le loro capacità.","Francois de La Rochefoucald",
"L'unico modo per sviluppare senso di responsabilità nella gente è affidarle delle responsabilità.","Kenneth Blanchard",
"Il miglior modo di vendicarci è di non assomigliare a chi ci ha offeso.","Marco Aurelio",
"Non appena sostituisci i pensieri negativi con altri positivi, comincerai ad avere risultati positivi.","Willie Nelson, cantante statunitense",
"La storia ha dimostrato che i vincitori più degni di nota hanno incontrato di solito ostacoli strazianti prima di trionfare. Hanno vinto perché si sono rifiutati di lasciarsi sconfiggere dalle sconfitte.","B.C. Forbes",
"Spesso l'uomo concentrandosi sui mezzi perde di vista lo scopo.","Arthur Schopenhauer",
"Pensa, credi, sogna e osa.","Walt Disney",
"Ogni giorno, quello che scegli, quello che pensi e quello che fai è ciò che diventi.","Eraclito",
"È piacevole incontrare gli occhi di una persona a cui si è appena fatto un dono.","Jean de la Bruyere",
"Il coraggio è credere in te stesso. E questo nessuno te lo potrà insegnare.","El Cordobes",
"Se si vuole che un'unione resista, bisogna averne cura giorno dopo giorno.","Jean Josipovici",
"Il buon legname non cresce facilmente: più forte è il vento, più robusto è l'albero.","J. Willard Marriot",
"Quando vivi in un luogo a lungo diventi cieco perché non osservi più nulla. Io viaggio per non diventare cieco.","Josef Koudelka",
"Non trascurate i dettagli: l'universo e tutto quello che esso contiene è composto di atomi, le particelle più piccole della materia.","Napoleon Hill",
"''Non hai paura di ammazzarti se fai un incidente?''<br />''No''. Si vive di più andando 5 minuti al massimo su una moto come questa, di quanto non faccia certa gente in una vita intera.''","Marco Simoncelli",
"Ogni cosa che facciamo è come una goccia nell'oceano, ma se non la facessimo l'Oceano avrebbe una goccia in meno.","Madre Teresa di Calcutta",
"Non potete separare la pace dalla libertà perché nessuno può essere in pace se non ha la sua libertà.","Malcolm X",
"Se vuoi sentirti ricco conta le cose che possiedi che il denaro non può comprare.","Seneca",
"La miseria è una malattia. Inutile ammirarla, parlarne, ed è pericoloso volerla curare. Stare lontani dal contagio è tutto quanto la persona saggia deve fare.","Ennio Flaiano",
"È meglio essere odiati per ciò che si è che essere amati per ciò che non si è.","André Gide",
"Chi vuol navigare finché non sia passato ogni pericolo non deve mai prendere il mare.","Thomas Fuller",
"Conta i fiori del tuo giardino, mai le foglie che cadono.","Romano Battaglia",
"È strana la vita, se ti rifiuti di accettare qualsiasi cosa tranne il meglio, spesso lo ottieni.","Somerset Maugham",
"La nostra più grande debolezza sta nella rinuncia. Il modo più sicuro per avere successo è sempre quello di provarci ancora una volta.","Thomas Alva Edison",
"La fonte di tutto quello che ti arriva e che puoi aspettarti dalla vita è la canzone che ti canti dentro. Se è un canto di prosperità, arriva prosperità, se è di povertà, povertà, se è di sventura, sventura.","Silvio Berlusconi",
"Amore è il desiderio di possedere eternamente il bene.","Platone",
"Apprezza le piccole cose, un giorno quando ti guarderai indietro realizzerai che sono state le cose più importanti.","Robert Brault",
"Le cicatrici sono il segno che è stata dura, ma il sorriso è il segno che ce l'hai fatta.","Madre Teresa di Calcutta",
"L'unico vero rischio nella vita è non voler correre alcun rischio.","Bambaren Sergio",
"L'intuizione di una donna è molto più vicina alla verità della certezza di un uomo.","Rudyard Kipling",
"Una delle più belle soddisfazioni di questa vita è che nessuno può sinceramente cercare di aiutare un altro senza aiutare e migliorare anche se stesso.","Ralph Waldo Emerson",
"L'unica saggezza è fare in modo che la nostra felicità e il nostro umore dipendano solamente da noi stessi.","Marcel Jouhandeau",
"Odio chi trova colpe anche nella sconfitta. La sconfitta è un dono non richiesto: accresce lo spirito comune e forgia l'anima.","Mario Kempes",
"Le persone viaggiano per stupirsi delle montagne, dei fiumi, delle stelle e passano accanto a se stesse senza meravigliarsi!","S. Agostino",
"Bombarda continuamente la tua mente con pensieri, parole, immagini della persona che vuoi essere.","Brian Tracy",
"Non importa quanto vai piano, l'importante è che non ti fermi.","Confucio",
"L'amore spesso non è ricambiato: ma l'odio sempre.","Ugo Bernasconi",
"Mantenetevi folli, e comportatevi come persone normali.","Paulo Coelho",
"Soltanto una cosa rende impossibile un sogno: la paura di fallire.","Paulo Coelho",
"Ogni momento è l'ultimo, perché è unico.","Marguerite Yourcenar",
"Tutti quelli che hanno raggiunto grandi risultati sono stati grandi sognatori.","Orison Swett Marden",
"Il tuo amore è per me come le stelle del mattino e della sera, tramonta dopo il sole e prima del sole risorge.","Johann Wolfgang von Goethe",
"Piove sul giusto e piove anche sull'ingiusto; ma sul giusto di più, perché l'ingiusto gli ruba l'ombrello.","Lord Bowen",
"È solo chi non fa niente che non fa errori, suppongo.","Joseph Conrad",
"Pensaci il sabato per non pentirti il Lunedì.","(proverbio)",
"Fate in modo di dare il buon esempio a tutti coloro con cui vivete e lavorate.","Ralph Waldo Emerson",
"Quando una persona felice entra in una stanza, è come se un'altra candela si accendesse.","Ralph Waldo Emerson",
"Rare sono le persone che usano la mente. Poche coloro che usano il cuore e uniche coloro che usano entrambi.","Rita Levi-Montalcini",
"Iniziare un nuovo cammino spaventa. Ma dopo ogni passo che percorriamo ci rendiamo conto di come era pericoloso rimanere fermi.","Roberto Benigni",
"Anche i sogni servono per diventare grandi.","S.R. Band",
"Non bisogna confondere la timidezza con l'umiltà; la vera umiltà consiste nel riconoscere che anche i migliori, nella trama dell'esistenza umana, sono solo frammenti di un tutto.","Napoleon Hill",
"Giovane è colui che alla sera si sente come al mattino, vecchio chi di mattina si sente come di sera.","Tadeusz Kotarbinski",
"È proprio la possibilità di realizzare un sogno che rende la vita interessante.","Paulo Coelho",
"La via per imparare è lunga se si procede per regole, breve e efficace se si procede per esempi.","Seneca",
"Decidete che una cosa si può e si deve fare e troverete il modo.","Abramo Lincoln",
"Tutti cercano un vero amico... Pochi si preoccupano di esserlo.","Anonimo",
"Non ci sono limiti per l'uomo che possiede la capacità di sognare.","Paulo Martins Netto",
"La giovinezza non è un dato anagrafico, è uno stato dell'anima, è una condizione dello spirito.","Silvio Berlusconi",
"Tanti a questo mondo apprendono soltanto ascoltando se stessi o almeno non sanno apprendere ascoltando gli altri.","Italo Svevo - La coscienza di Zeno",
"Il destino è un'invenzione della gente fiacca e rassegnata.","Ignazio Silone",
"Lascio agli altri la convinzione di essere i migliori, per me tengo la certezza che nella vita si può sempre migliorare.","Marilyn Monroe",
"Non si fa il proprio dovere perché qualcuno ci dica grazie, lo si fa per principio, per se stessi, per la propria dignità.","Oriana Fallaci",
"Coraggio è ciò che ci vuole per alzarsi a parlare. Coraggio è anche ciò che ci vuole per sedersi ad ascoltare.","Winston Churchill",
"Chi è saggio parla solo quando è certo che chi ascolta è in grado di capire.","Georges Ivanovi? Gurdjieff",
"I bambini sono come i marinai: dovunque si posano i loro occhi, è l?immenso.","Christian Bobin",
"Un solo raggio di sole è sufficiente per cancellare milioni di ombre.","S. Francesco d'Assisi",
"Il sorriso è la distanza più breve fra due persone.","Victor Borge",
"Vivete; se volete credermi, non aspettate domani. Cogliete fin da oggi le rose della vita.","Pierre de Ronsard",
"Chi vuole mettersi in viaggio verso le stelle non si guardi intorno in cerca di compagnia.","Christian Friedrich Hebbel",
"Pochissimi sanno essere liberi e pochissimi sanno cosa vuol dire esserlo.","Marguerite Yourcenar",
"Le passioni fanno vivere l'uomo, la saggezza lo fa soltanto vivere a lungo.","Sébastien-Roch Nicolas de Chamfort",
"La più grande scoperta della mia generazione è che gli esseri umani possono modificare la propria vita modificando il proprio atteggiamento mentale.","William James",
"Nella vita esistono due grandi obiettivi: il primo, ottenere ciò che si vuole, e il secondo, goderselo. Solo i membri più saggi dell'umanità riescono a fare la seconda cosa.","Logan Pearsall Smith",
"La vera misura di un uomo si vede da come tratta qualcuno da cui non può ricevere assolutamente nulla in cambio.","Samuel Johnson",
"Esiste un'isola di opportunità all'interno di ogni difficoltà.","Demostene",
"Esistono solo 3 colori, 10 cifre e 7 note; è ciò che facciamo con loro che è importante.","Ruth Ross",
"Non sono le montagne a stancare gli uomini che le scalano, ma i sassolini nelle loro scarpe.","Kastajir",
"La misura dell'amore è amare senza misura.","S. Agostino",
"La qualità del vostro lavoro è, a lungo termine, il fattore decisivo per stabilire quanto il mondo valuti i vostri servizi.","Orison Swett Marden",
"Il mezzo più efficace di ottener fama è quello di far credere al mondo di esser già famoso.","Giacomo Leopardi",
"Come raggiungere un traguardo? Senza fretta ma senza sosta.","Johann Wolfgang von Goethe",
"La vita non è aspettare che passi la tempesta, ma imparare a ballare sotto la pioggia.","Mahatma Gandhi",
"La maggior parte delle sfortune sono il risultato del tempo utilizzato male.","Napoleon Hill",
"Non si desidera ciò che è facile ottenere.","Ovidio",
"Se qualcuno ti tradisce una volta, è un suo errore, se qualcuno ti tradisce due volte è un tuo errore.","Eleanor Roosvelt",
"Si raccoglie sempre avendo seminato, anche se a volte più tardi di quando pensiamo.","Miao Yin",
"Non fidatevi delle apparenze: il tamburo, con tutto il fracasso che fa, non è ripieno di nulla.","dal 'Corano'",
"Tutti dimenticano i concetti base: le persone non ti ameranno a meno che non le ami tu per primo.","Pat Carroll",
"Sii ben contento di esistere. Nessun momento sarà più importante di quello in cui, alla fine dei tuoi giorni, mediterai sulla tua vita.","Paul Wilson",
"L'amore è come la pioggerella d'autunno: cade piano ma fa straripare i fiumi!","(proverbio africano)",
"Le cose che impariamo con passione, non le dimenticheremo mai.","Alfred Mercier",
"Il vero signore è simile a un arcere: se manca il bersaglio, cerca la causa di questo in se stesso.","Confucio",
"La lettura è per la mente ciò che l'esercizio è per il corpo.","Joseph Addison",
"Dio non poteva essere ovunque, perciò ha creato le madri.","(proverbio ebraico)",
"La mente dell'uomo che si espande con una nuova idea non torna più alle sue dimensioni originarie.","Oliver Wendell Holmes",
"Bisogna essere dei grandi ignoranti per rispondere a tutto quello che ci viene chiesto.","Voltaire",
"Sicuramente i più coraggiosi sono coloro che hanno la visione più chiara di ciò che li aspetta, così della gloria come del pericolo, e tuttavia l'affrontano.","Tucidide",
"Il buon pastore deve tosare le pecore, non divorarle.","Svetonio",
"Chi ha un perché abbastanza forte, può superare qualsiasi come.","Friedrich Nietzsche",
"Grandi menti parlano di idee, menti mediocri parlano di fatti, menti piccole parlano di persone.","Eleanor Roosevelt",
"La libertà non sta nello scegliere tra bianco e nero, ma nel sottrarsi a questa scelta prescritta.","Theodor Adorno",
"Le favole non dicono ai bambini che i draghi esistono. Perché questo i bambini lo sanno già. Le favole dicono ai bambini che i draghi possono essere sconfitti.","Gilbert Keith Chesterton",
"Prima ti ignorano, poi ti deridono, poi ti combattono. Poi vinci.","Mahatma Gandhi",
"Ho deciso di essere felice perché fa bene alla mia salute.","Voltaire",
"Ricorda, se non riesci a trovare il Natale nel tuo cuore, non potrai trovarlo sicuramente sotto un albero.","Charlotte Carpenter",
"Se giudichi le persone, non hai il tempo di amarle.","Madre Teresa di Calcutta",
"La nostra gloria maggiore non consiste nel non sbagliare, ma nel risollevarsi ogni volta che cadiamo.","Confucio",
"L'abitudine può essere il migliore servitore o il peggiore padrone.","Nathaniel Emmons",
"Se continui a fare quello che hai sempre fatto, continuerai ad ottenere ciò che hai sempre avuto.","Warren G. Bennis",
"Io non amo la gente perfetta, quelli che non sono mai caduti o che non hanno mai inciampato. A loro non si è svelata la bellezza della vita.","Boris Pasternak",
"Amatevi l'un con l'altra, ma non fatene una prigione d'amore.","Kahlil Gibran",
"Il vero io è quello che tu sei, non quello che gli altri hanno fatto di te.","Paulo Coelho",
"La felicità è come una farfalla: se l'insegui non riesci mai a prenderla, ma se ti metti tranquillo può anche posarsi su di te.","Nathaniel Hawthorne",
"Non abbassare mai gli occhi sulla vita anche se il sonno della resa è più forte.","Biagio Antonacci",
"Siate affamati, siate folli.","Steve Jobs",
"Nessun uomo grande vive invano. La storia del mondo non è altro che la biografia di grandi uomini.","Thomas Carlyle",
"La cultura è l'unico bene dell'umanità che, diviso fra tutti, anziché diminuire diventa più grande.","Hans Georg Gadamer",
"La vita ha 4 sensi: amare, soffrire, lottare e vincere. Chi ama soffre, chi soffre lotta, chi lotta vince. Ama molto, soffri poco, lotta tanto, vinci sempre.","Oriana Fallaci",
"Ho capito che avendo fiducia in me stesso e in ciò che penso, solitamente ottengo grandi cose.","Charles F. Kettering",
"Se vuoi che i tuoi sogni si avverino, la prima cosa da fare è svegliarsi.","J. M. Power",
"Non saper rimediare a un errore è cosa peggiore dell'errore stesso.","Baltasar Gracian",
"Non è mai troppo tardi per essere quello che sareste potuti essere.","George Eliot",
"La somma della nostra vita sono le ore in cui abbiamo amato.","Wilhelm Busch",
"C'è una crepa in ogni cosa. Ed è da lì che entra la luce.","Leonard Cohen",
"Fa del tuo meglio, quello che semini lo raccoglierai più tardi.","Og Mandino",
"Fallimento è desistere di tentare.","Myles Munroe",
"Se ci tengo a fare qualcosa, non lo chiamo lavoro.","Richard Bach",
"Gli uomini si sbagliano, i grandi uomini confessano di essersi sbagliati.","Voltaire",
"Credi alla forza dei tuoi sogni e loro diventeranno realtà.","Sergio Bambaren",
"Nessuno può farti sentire inferiore senza il tuo consenso.","Eleanor Roosvelt",
"Esiste merito senza successo ma non esiste successo senza qualche merito.","Francois de La Rochefoucald",
"L'ingratitudine più odiosa, ma più antica e più comune, è quella dei figli verso i loro genitori.","Luc de Clapiers de Vauvenargues",
"Come una candela ne accende un'altra e così si trovano accese migliaia di candele, così un cuore ne accende un altro e così si accendono migliaia di cuori.","Lev N. Tolstoj",
"Non esiste curva dove non si possa sorpassare.","Ayrton Senna",
"Non ti addormentare MAI pensando che una cosa sia impossibile a farsi. Rischi di essere svegliato dal rumore di qualcuno che sta appunto facendola?","Anonimo",
"Molto spesso siamo noi i peggiori nemici di noi stessi, con il vizio che abbiamo di erigere ostacoli sul cammino che conduce al successo e alla felicità.","Louis Binstock",
"Il tempo è galantuomo e rimette ogni cosa al suo posto.","Voltaire",
"Il tuo cuore è libero, abbi il coraggio di seguirlo!","dal film ''Braveheart''",
"È lo sforzo continuo e costante che supera ogni resistenza ed ostacolo.","Claude M. Bristol",
"La gioia non è nelle cose, è in noi.","Richard Wagner",
"Il rivoluzionario inventa le idee, quando le ha esaurite il conservatore le fa sue.","Mark Twain",
"Se ami quello che fai, non sarà mai un lavoro.","Confucio",
"Alcuni parlano, altri ripetono.","Bruno de Finetti",
"Chi ha coraggio di ridere, è padrone del mondo.","Giacomo Leopardi",
"Tutti abbiamo dentro un'insospettata riserva di forza che emerge quando la vita ci mette alla prova.","Isabel Allende",
"La fortuna non è sempre e tutta opera del caso.","Baltasar Gracian",
"La timidezza nell'esecuzione produce il fallimento delle imprese temerarie.","Luc de Clapiers de Vauvenargues",
"Una semplice filosofia di vita: se dai agli altri gli altri daranno a te.","Richard Bach",
"Consiglio che una volta sentii dare a un giovane: 'Fai sempre quel che hai paura di fare'.","Ralph Waldo Emerson",
"Un albero è conosciuto per i suoi frutti, un uomo per le sue azioni. Una buona azione non è mai perduta. Colui che semina cortesia miete amicizia, colui che pianta gentilezza raccoglie amore.","S. Basilio",
"Insegui ciò che ami, o finirai per amare ciò che trovi.","Carlo Collodi - Pinocchio",
"L'universo ci aiuta sempre a lottare per i nostri sogni, per quanto sciocchi possano sembrare. Perché sono i nostri, e soltanto noi sappiamo quanto ci costa sognarli.","Paulo Coelho",
"Noi ci tormentiamo meno per divenire felici che per far credere che lo siamo.","Francois de La Rochefoucald",
"Il dolore è il gran maestro degli uomini. Sotto il suo soffio si sviluppano le anime.","Marie von Ebner-Eschenbach",
"Chi crea non presta attenzione a chi lo critica, a meno che non diventi arido inventore.","Silvio Berlusconi",
"Sii sempre la versione originale di te stesso, piuttosto che la brutta copia di qualcun altro.","Judy Garland",
"Ricordati le 3 'R': rispetto per te stesso, rispetto per gli altri, responsabilità delle tue azioni.","Anonimo",
"La nobiltà non è un diritto di nascita, ma la si conquista con le proprie azioni!","al film ''Robin Hood, principe dei ladri''",
"Troppe volte l'urgente non lascia tempo per l'importante.","Mafalda - Quino",
"Amare è il tentativo di trasformare un sogno in realtà.","Theodore Reik",
"Il procrastinare è l'assassino naturale dell'opportunità.","Victor Kiam",
"È proprio quando gli dei vogliono punirci, che esaudiscono le nostre preghiere.","Oscar Wilde",
"La follia sta nel fare sempre la stessa cosa apettandosi risultati diversi!","Albert Einstein",
"Mai nessuna notte è tanto lunga da non permettere al sole di sorgere.","Paulo Coelho",
"Vivi come se dovessi morire domani. Impara come se dovessi vivere per sempre.","Mahatma Gandhi",
"Un amore crollato, ricostruito, cresce forte, leggiadro, grande più di prima.","William Shakespeare",
"Ciò che conta non è fare molto, ma mettere molto amore in ciò che si fa.","Madre Teresa di Calcutta",
"Non si è mai sentito di grandi progressi dell'umanità compiuti senza la collaborazione di altri. Persino un grande artista come Michelangelo per realizzare il suo lavoro dovette contare sull'aiuto di assistenti, artigiani e mecenati.","Napoleon Hill",
"Colui che crede in se stesso vive coi piedi fortemente poggiati sulle nuvole.","Ennio Flaiano",
"Fidarsi della bontà altrui è una prova non piccola della propria bontà.","Michel de Montaigne",
"Non essere impaziente: cammina quanto è il tempo di camminare e mangia quanto è il tempo di mangiare.","Paulo Coelho",
"Se le acque sono calme, riflettono la luna. Allo stesso modo, se noi ci plachiamo, riflettiamo il divino.","pensiero tao",
"Ci sono persone che si credono speciali. Altre, silenziosamente, lo sono.","Samuel Johnson",
"Si può mentire con la bocca: ma con l'espressione che si ha in quel momento si dice pur sempre la verità.","Friedrich Nietzsche",
"Un grande pilota sa navigare anche con la vela rotta.","Seneca",
"Qualsiasi stupido può criticare, condannare e lamentarsi, e quasi tutti gli stupidi lo fanno. Ci vuole invece carattere ed auto-controllo per ascoltare, comprendere e perdonare.","Dale Carnegie",
"La vita sceglie la musica, noi scegliamo come ballarla.","John Galsworthy",
"L'esperienza ti suggerisce cosa fare, la sicurezza ti permette di farlo.","Stan Smith",
"Nessuno è più schiavo di colui che si ritiene libero senza esserlo.","Johann Wolfgang von Goethe",
"Punta a conquistare la luna. Se non ci sarai riuscito, avrai vagabondato tra le stelle.","Les Brown",
"Non ci può essere grandezza senza semplicità.","Lev N. Tolstoj",
"La follia è l'unica cosa capace di prolungare la giovinezza e tenere lontano la molesta vecchiaia.","Erasmo da Rotterdam",
"Abbi cura dei tuoi ricordi perché non puoi viverli di nuovo.","Bob Dylan",
"Quando sono andato a scuola, mi hanno chiesto cosa volessi diventare da grande. Ho risposto ''felice''. Mi dissero che non avevo capito l'esercizio e io risposi che loro non avevano capito la vita.","John Lennon",
"Sii il cambiamento che vuoi vedere nel mondo.","Mahatma Gandhi",
"La vendetta è un piacere che dura solamente un giorno; la generosità, un sentimento che può portare la felicità per sempre.","Friedrich Rickbert",
"Non indugiare sui problemi, ma concentrati sulle soluzioni. Risolvi quello che puoi, non lamentarti perché non puoi.","Michael Angier",
"Fai quello che puoi con quello che hai, nel posto in cui sei.","Theodore Roosevelt",
"Laddove tutti pensano allo stesso modo, nessuno pensa un gran che!","Walter Lippmann",
"La vita è come un'eco: se non ti piace quello che ti rimanda, devi cambiare il messaggio che invii.","James Joyce",
"Non seguire il sentiero: tracciane uno nuovo e lascia la tua impronta da seguire.","Anonimo",
"Che c'è di più duro della pietra e di più molle dell'acqua? Eppure la molle acqua scava la dura pietra.","Ovidio",
"Abbi il coraggio di servirti della tua intelligenza.","Immanuel Kant",
"Nel momento più buio della sconfitta, la vittoria potrebbe essere più vicina.","William McKinley",
"Quando perdiamo il diritto di essere differenti, perdiamo il privilegio di essere liberi.","Charles Hughes",
"La vera libertà individuale non può esistere senza sicurezza economica ed indipendenza. La gente affamata e senza lavoro è la pasta di cui sono fatte le dittature.","Franklin Delano Roosevelt",
"Se le piante sono sicure che la primavera verrà, perché noi, esseri umani, non crediamo che un giorno saremo capaci di raggiungere e ottenere tutto ciò che vogliamo?","Kahlil Gibran",
"Considera perso quel giorno in cui il sole al tramonto ti trova senza che tu abbia fatto una buona azione.","Napoleon Hill",
"Chi crede di sapere tutto non ha modo di scoprire che non lo sa per niente.","Leo Buscaglia",
"Le occasioni abbondano per ogni individuo nel sentiero della vita; possono non essere quelle che preferite, ma ogni volta che ne mettete a frutto una, questa conduce a un'opportunità più grande e migliore.","Napoleon Hill",
"Ogni persona che incontri sta combattendo una battaglia di cui non sai nulla. Sii gentile. Sempre.","Platone",
"Preferisco un fallimento alle mie condizioni che un successo alle condizioni altrui.","Tom Waits",
"Se manca qualcosa alla tua vita è perché non hai guardato abbastanza in alto.","Romano Battaglia",
"La libertà non è una cosa che si possa dare; la libertà uno se la prende, e ciascuno è libero quanto vuole esserlo.","James Baldwin",
"Il tuo cuore è un gabbiano che vola libero nei cieli della vita. Lascialo andare senza paura, ti saprà condurre alla felicità.","Sergio Bambaren",
"Meglio nessun successo che nessuna decisione.","Karl Heinrich Waggerl",
"Conosco una sola libertà ed è la libertà della mente.","Antoine de St. Exupery",
"Il bel tempo e l'amore sono due cose di cui non possiamo mai essere certi.","Alice Hoffman",
"Non c'è esercizio migliore per il cuore che stendere la mano e aiutare gli altri ad alzarsi.","Henry Ford",
"Non c'è cuscino più morbido di una coscienza tranquilla.","Ken Blanchard",
"La perseveranza è il duro lavoro che fai dopo che ti sei stancato del duro lavoro che hai fatto.","Newt Gingrich",
"Perdere l'entusiasmo provoca rughe nell'anima.","Samuel Ullman",
"Tieniti lontano dalle persone che cercano di sminuire le tue ambizioni. La gente meschina lo fa sempre, ma chi è veramente grande ti fa capire che anche tu puoi diventare grande.","Mark Twain",
"È meglio morire in piedi che vivere in ginocchio.","Emiliano Zapata",
"L'avversità restituisce agli uomini tutte le virtù che la prosperità toglie loro. ","Eugène Delacroix",
"Gli unici modi per fuggire dalla vita sono la pazzia e l'ironia.","Luigi Pirandello",
"È più facile insegnare che educare, perché per insegnare basta sapere, mentre per educare è necessario essere.","Alberto Hurtado",
"Presto o tardi coloro che vincono sono coloro che credono di poterlo fare.","Richard Bach",
"Essere capiti vuol dire essere presi e accettati per quello che siamo.","Natalia Ginzburg",
"La vera felicità e soddisfazione nella vita dipende da come vivi ciò che ti appassiona veramente. Solo vivendo con passione raggiungerai la felicità a cui sei destinato.","Paul Bauer",
"Quando siamo a terra possiamo guardare solo in alto.","Roger Ward Babson",
"Quando scoprirò chi sono, sarò un uomo libero.","Ralph Ellison",
"Non c'è nulla che infonde una felicità cosi' profonda e completa quanto il mistero e la meraviglia di una vita eccitante perpetuamente rinnovata.","Norman Vincent Peale",
"I premi della vita si trovano al termine di ogni viaggio, non agli inizi; e non mi è dato sapere quanti passi sono necessari per raggiungere la meta.","Og Mandino",
"Ci sono persone che lasciano un segno indelebile nella propria vita e non sono quelle che danno il meglio di sé, ma quelle che riescono a tirare fuori il meglio di te.","Paola Melone",
"L'equipe migliore è composta da tre persone, due delle quali assenti.","Winston Churcill",
"Il tempo è una grande metafora della vita: a volte è bello, a volte è brutto, e non c'è niente che tu possa fare, se non portarti un ombrello o metterti a ballare sotto la pioggia.","Terri Guillemets",
"Tutti sorridono nella stessa lingua.","Morris Mandel",
"Tuo primo dovere è di far felice te stesso. Se sei felice, fai felici anche gli altri. Il felice vuole solo vedersi dei felici d'attorno.","L. Feuerbach",
"L'entusiasmo trova le opportunità, l'energia crea la maggior parte di queste.","George M. Adams",
"Ho visto la faccia dell'angelo nel marmo e ho semplicemente scolpito fino a renderlo libero.","Michelangelo",
"Il sorriso è il cibo dell'anima.","Anonimo",
"Non amo le persone che si esibiscono ma stravedo per quelle che una volta arrivate in cima, rimangono uguali al giorno prima.","Giorgio Faletti",
"Per chi è capace di un po? di disciplina e sa seguire alcune regole, far soldi è sempre stata una cosa semplice.","P.T Barnum",
"Se l'opportunità non bussa, costruisciti una porta.","Milton Berle",
"Quando si vede un gigante, si ponga mente anzitutto alla posizione del Sole e si badi se non sia l'ombra di un pigmeo.","Novalis",
"Non c'è nulla di così alto cui la persona forte non possa poggiare la propria scala.","Shiller",
"La forza non arriva dalle vittorie. La lotta e le sfide sviluppano la tue forze. Quando attraversi le difficoltà e decidi di non arrenderti, quella è forza.","Arnold Schwarzenegger",
"Colui che ha il coraggio di ridere è padrone del mondo quasi quanto chi è pronto a morire.","Giacomo Leopardi",
"Non bisogna perdere la capacità di stupirsi, perché altrimenti il mondo e la nostra stessa vita diventerebbe un'abitudine.","J. Gaarder",
"La nostra vita comincia a finire il giorno che diventiamo silenziosi sulle cose che contano.","Martin Luther King",
"Se è vero che la tua mente può farti ammalare, e in effetti lo è, ricordati che può anche farti stare bene.","Napoleon Hill",
"Se sarete disposti a lavorare di più e meglio di quello per cui siete pagati, prima o poi riceverete l'interesse composto del vostro investimento. Ogni seme di servizio utile che pianterete non potrà che germogliare e premiarvi con abbondanza di frutti.","Napoleon Hill",
"Una puntura di zanzara prude meno quando sei riuscito a schiacciare la zanzara.","Ugo Ojetti",
"Gli sforzi che facciamo per ottenere qualcosa sono direttamente proporzionali ai risultati: è  l'intensità dello sforzo a condizionare il risultato.","Og Mandino",
"Ho imparato che un uomo ha il diritto di guardarne un altro dall'alto al basso solamente quando deve aiutarlo ad alzarsi.","Gabriel Garcìa Màrquez",
"Ascolta ciò che conosci piuttosto che ciò di cui hai paura.","Richard Bach",
"Nessuna grande opera viene creata in un istante.","Epitteto",
"Volere è poco, occorre volere con ardore per raggiungere lo scopo.","Ovidio",
"Le grandi opere non si realizzano con la forza, ma con la perseveranza.","Samuel Johnson",
"La mia vita è un insieme di note musicali che il tuo cuore trasforma in melodia. Vorrei che fossimo sempre capaci di vivere tutto ciò che di sacro vi è in ogni istante.","Kahlil Gibran",
"Per poter pensare con fiducia al futuro, bisogna costruire basi solide nell'oggi.","Milan Kundera",
"Ma il niente è da preferire al soffrire? Io perfino nelle pause in cui piango sui miei fallimenti, le mie delusioni, i miei strazi, concludo che soffrire sia da preferire al niente.","Oriana Fallaci",
"Le difficoltà crescono a misura che ci si avvicini alla meta. Seminare non è così difficile come raccogliere.","Johann Wolfgang von Goethe",
"Agli esami gli sciocchi fanno le domande a cui i saggi non sanno rispondere.","Oscar Wilde",
"Essere potenti è come essere una donna. Se hai bisogno di dimostrarlo vuol dire che non lo sei.","Margaret Thatcher",
"La facilità non genera felicità, mai.","Massimo Gramellini",
"Quando l'ultimo albero sarà tagliato, l'ultimo fiume inquinato, l'ultimo pesce pescato, scoprirete che il denaro non si può mangiare.","Seattle, capo della tribu' Suquamish",
"La perplessità è l'inizio della conoscenza.","Khalil Gibran",
"Siamo tutti nati nel fango, ma alcuni di noi guardano alle stelle.","Oscar Wilde",
"L'uomo non può scoprire nuovi oceani finché non ha il coraggio di perdere di vista la costa.","Anonimo",
"C'è qualcuno seduto all'ombra oggi perché qualcun altro ha piantato un albero molto tempo fa.","Warren Buffett",
"Dei beni ai quali non è mai venuto in mente a un uomo di aspirare, egli non sente la mancanza.","Arthur Schopenhauer",
"Non importa quello che stai guardando ma quello che riesci a vedere.","Henry David Thoreau.",
"Nei momenti sereni ricordati di temere sempre le avversità e nelle avversità ricordati di sperare sempre in cose migliori.","Catone",
"Felice è soltanto l'anima che ama.","Johann Wolfgang von Goethe",
"Nessuno va in paradiso con gli occhi asciutti.","Thomas Adams",
);
